# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Purchase.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14proto/Purchase.proto\x12\x0fitalo.dev.proto"A\n\x08Purchase\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\x12\n\ntotal_cost\x18\x02 \x01(\x01\x12\x13\n\x0b\x63ustomer_id\x18\x03 \x01(\tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.Purchase_pb2", globals())

if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _PURCHASE._serialized_start = 41
    _PURCHASE._serialized_end = 106
# @@protoc_insertion_point(module_scope)
